markdown: kramdown
plugins:
 - jekyll-paginate
permalink: /:title/
url: blog.xulihang.me
name: xulihang's blog
author: xulihang
qq: 110
email: xulihanghai@163.com
duoshuo: xulihang
beian: 
51la: 16741573
weibo: 2794687610
github: xulihang
highlighter: pygments
paginate: 20
about: "在Github上的Blog。"
