markdown: kramdown
plugins:
 - jekyll-paginate
 - jekyll-relative-links
permalink: /:title/
url: https://blog.xulihang.me
baseurl: ""
relative_links:
  enabled: true
  collections: true
name: xulihang's blog
author: xulihang
qq: 110
email: xulihanghai@163.com
duoshuo: xulihang
beian: 
51la: 
weibo: 2794687610
github: xulihang
highlighter: pygments
paginate: 20
about: "在Github上的Blog。"
