markdown: rdiscount
permalink: /:title/
url: xulihang.wicp.net
name: xulihang's blog
author: xulihang
qq: 110
email: xulihanghai@163.com
duoshuo: xulihang
beian: 
cnzz: 
weibo: 
github: xulihang
pygments: true
safe: true
paginate: 20
about: "在Github上的Blog。"
